name: tests

on:
  push:
    branches:
      - dev
      - main
      - master
      - next
      - feat/**
  pull_request:
    branches:
      - master
      - main
  schedule:
    - cron: '0 0 20 * *'

jobs:
  tests:
    runs-on: codebuild-laravel-blogger-api-demo-${{ github.run_id }}-${{ github.run_attempt }}

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: true
      matrix:
        php: ['8.2']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, memcached
          tools: composer:v2
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Execute tests
        run: composer test -- --coverage-clover=coverage.xml
        env:
          APP_KEY: "base64:z9RyCIoLo+TkR0WCoc8b0gqw4tEGbwms2zn3BCrwUz8="
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
          DB_DATABASE: laravel
